# Generated by Django 2.2.4 on 2020-10-20 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='profile_image',
        ),
    ]
